name:                json-transformer
version:             0.1.0.0
github:              "hadenir/json-transformer"
license:             BSD3
author:              "Konrad Hadenir Brzózka"
maintainer:          "example@example.com"
copyright:           "2022 Hadenir"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/hadenir/haskell/tree/main/json-transformer#readme>

dependencies:
- base >= 4.7 && < 5
- containers
- attoparsec
- text
- pipes

library:
  source-dirs: src
  default-extensions:
    - OverloadedStrings

executables:
  jsot:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - json-transformer

tests:
  jsot-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - json-transformer
